apiVersion: v1
kind: ServiceAccount #tạo service account có tên là app-sa
metadata:
  name: app-sa
  namespace: demo
# ServiceAccount app-sa được gán Role app-role, nên được phép get và list Pod trong namespace demo.
# ServiceAccount là danh tính (identity) mà Pod sử dụng để nói chuyện với Kubernetes API((API Server) là "cửa chính" của Kubernetes.)
#khi pod chạy thì k8s sẽ gắn cho pod 1 thẻ nhân viên là app-sa
# ServiceAccount đại diện cho toàn bộ Pod khi Pod giao tiếp với Kubernetes API.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role #tạo role có tên là app-role
  namespace: demo
rules:
- apiGroups: [""] #core API group như pods, services, configmaps, secrets,...
  resources: ["pods"]
  verbs: ["get", "list"] #quyền get và list pods
#role đang gán cho service account app-sa quyền get và list pods trong namespace demo
#và chưa có pod nào sử dụng service account này nên chưa có pod nào được quyền get và list pods
#pod thông qua service account sẽ có một tấm thẻ nhân viên để nói chuyện với API Server, tấm thẻ này gọi là token
#nó được phép hỏi k9s api để xem ds pod or tt pod
#Role cấp quyền truy cập Kubernetes API.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #tạo rolebinding để gán role app-role cho service account app-sa
metadata:
  name: app-rolebinding
  namespace: demo
subjects:
- kind: ServiceAccount #gán role cho service account
  name: app-sa
  namespace: demo
roleRef: #tham chiếu đến role app-role
  kind: Role #gán role app-role
  name: app-role
  apiGroup: rbac.authorization.k8s.io