apiVersion: v1
kind: ServiceAccount #tạo service account có tên là app-sa
metadata:
  name: app-sa
  namespace: demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role #tạo role có tên là app-role
  namespace: demo
rules:
- apiGroups: [""] #core API group như pods, services, configmaps, secrets,...
  resources: ["pods"]
  verbs: ["get", "list"] #quyền get và list pods

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #tạo rolebinding để gán role app-role cho service account app-sa
metadata:
  name: app-rolebinding
  namespace: demo
subjects:
- kind: ServiceAccount #gán role cho service account
  name: app-sa
  namespace: demo
roleRef: #tham chiếu đến role app-role
  kind: Role #gán role app-role
  name: app-role
  apiGroup: rbac.authorization.k8s.io